services:
  - type: web
    name: ruahnote
    runtime: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_POOLER_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
